services:
  postgres:
    image: postgres:18.1
    container_name: db
    secrets:
      - db_user
      - db_name
    env_file:
      - ./configs/postgres.env
    volumes:
      - ./init/schema/001.init.up.sql:/docker-entrypoint-initdb.d/001.init.up.sql
      - ./postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/db_user) -d $(cat /run/secrets/db_name)"]
      interval: 5s
      timeout: 10s
      retries: 20

  pr-assign-service:
    build: .
    image: pr-assigning-service:1.0
    container_name: server
    env_file:
      - ./configs/server.env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

secrets:
  db_user:
    file: ./init/secrets/db_user
  db_name:
    file: ./init/secrets/db_name